apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: {{ .Values.namespace }}
data:
  elasticsearch.yml: |
    cluster.name: logging-cluster
    network.host: 0.0.0.0
    discovery.type: single-node
    xpack.security.enabled: false