appName: user-service
projectNamespace: otus-msa
replicaCount: 1
image:
  repository: stepanych58/user-service
  pullPolicy: IfNotPresent
  tag: ""
imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations:
    - nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: ""
podAnnotations: { }
podLabels: { }
podSecurityContext: { }
securityContext: { }
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
userServiceSwaggerIngress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: arch.homework
      paths:
        - path: /otus-user-service/(.*)
          pathType: ImplementationSpecific
  tls: [ ]
userServiceApiIngress:
  enabled: true
  className: "nginx"
  annotations:
   kubernetes.io/ingress.class: nginx
   kubernetes.io/tls-acme: "true"
  hosts:
    - host: arch.homework
      paths:
        - path: /user-service(/.*)?
          pathType: ImplementationSpecific
  tls: [ ]
resources: { }
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: [ ]
volumeMounts: [ ]
nodeSelector: { }
tolerations: [ ]
affinity: { }

apiCaller:
  enabled: true

env:
  JAVA_TOOL_OPTIONS: "-XX:+UseSharedSpaces"
