apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-cm
  labels:
    {{- include "user-service-chart.labels" . | nindent 4 }}
  {{- with .Values.userServiceSwaggerIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Values.projectNamespace }}
data:
  springdoc.swagger-ui.config-url: /otus-user-service/v3/api-docs/swagger-config
  springdoc.swagger-ui.url: /otus-user-service/v3/api-docs
  springdoc.swagger-ui.urls.url: /otus-user-service/v3/api-docs
  spring.aot.enabled: 'true'